### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Dpbm** [Dpbm/qiskit-metal-docker#8]
- [x] add docker-compose
- [ ] add alpine based image
- [ ] basic project template
- [ ] fix the version on Dockerfiles
